import type { ResumeTemplate } from "../types/resume"

export const resumeTemplates: ResumeTemplate[] = [
  {
    id: "modern-blue",
    name: "Modern Blue",
    description: "Clean and professional with blue accents",
    colorScheme: {
      primary: "#2563eb",
      secondary: "#1e40af",
      accent: "#3b82f6",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "elegant-green",
    name: "Elegant Green",
    description: "Sophisticated design with green highlights",
    colorScheme: {
      primary: "#059669",
      secondary: "#047857",
      accent: "#10b981",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "creative-purple",
    name: "Creative Purple",
    description: "Bold and creative with purple theme",
    colorScheme: {
      primary: "#7c3aed",
      secondary: "#6d28d9",
      accent: "#8b5cf6",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "professional-gray",
    name: "Professional Gray",
    description: "Timeless and professional gray design",
    colorScheme: {
      primary: "#374151",
      secondary: "#1f2937",
      accent: "#6b7280",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "vibrant-orange",
    name: "Vibrant Orange",
    description: "Energetic and modern with orange accents",
    colorScheme: {
      primary: "#ea580c",
      secondary: "#c2410c",
      accent: "#fb923c",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "minimalist-teal",
    name: "Minimalist Teal",
    description: "Clean minimalist design with teal highlights",
    colorScheme: {
      primary: "#0d9488",
      secondary: "#0f766e",
      accent: "#14b8a6",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "bold-red",
    name: "Bold Red",
    description: "Strong and confident with red theme",
    colorScheme: {
      primary: "#dc2626",
      secondary: "#b91c1c",
      accent: "#ef4444",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "soft-pink",
    name: "Soft Pink",
    description: "Gentle and approachable with pink tones",
    colorScheme: {
      primary: "#ec4899",
      secondary: "#db2777",
      accent: "#f472b6",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "corporate-navy",
    name: "Corporate Navy",
    description: "Traditional corporate style with navy blue",
    colorScheme: {
      primary: "#1e3a8a",
      secondary: "#1e40af",
      accent: "#3b82f6",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "fresh-lime",
    name: "Fresh Lime",
    description: "Fresh and modern with lime green accents",
    colorScheme: {
      primary: "#65a30d",
      secondary: "#4d7c0f",
      accent: "#84cc16",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "warm-amber",
    name: "Warm Amber",
    description: "Warm and inviting with amber highlights",
    colorScheme: {
      primary: "#d97706",
      secondary: "#b45309",
      accent: "#f59e0b",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "cool-indigo",
    name: "Cool Indigo",
    description: "Cool and sophisticated indigo design",
    colorScheme: {
      primary: "#4f46e5",
      secondary: "#4338ca",
      accent: "#6366f1",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "earth-brown",
    name: "Earth Brown",
    description: "Natural and grounded with brown tones",
    colorScheme: {
      primary: "#92400e",
      secondary: "#78350f",
      accent: "#a16207",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "ocean-cyan",
    name: "Ocean Cyan",
    description: "Refreshing ocean-inspired cyan theme",
    colorScheme: {
      primary: "#0891b2",
      secondary: "#0e7490",
      accent: "#06b6d4",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
  {
    id: "sunset-rose",
    name: "Sunset Rose",
    description: "Warm sunset colors with rose gold accents",
    colorScheme: {
      primary: "#be185d",
      secondary: "#9d174d",
      accent: "#ec4899",
      text: "#1f2937",
      background: "#ffffff",
    },
    preview: "/placeholder.svg?height=300&width=200",
  },
]
